// What a phone needs to install the game from its home screen: the web app manifest, the icons, and
// the service worker that keeps it playable with no network. tools/build.ts writes these into dist/
// beside index.html, which links them, and tools/server.ts serves them in development, so the page
// asks for the same names in both.
//
// Like the sounds and the sprites, the icons are drawn rather than kept as asset files: the G of the
// engine's pixel font, outlined the way the title screen draws GAUNTLET, on the game's background,
// and encoded as PNG with nothing but node:zlib.
import zlib from 'node:zlib';
import crypto from 'node:crypto';

/** The page background in index.html; also the splash screen and the status bar. */
const BACKGROUND = '#0b0a10';
const BG = [0x0b, 0x0a, 0x10], GOLD = [0xff, 0xd0, 0x40], OUTLINE = [0x3a, 0x1c, 0x00];
/** The G of src/lib/engine/text.ts, which keeps its glyphs to itself. */
const G = ['.####', '#....', '#....', '#.###', '#...#', '#...#', '.####'];
/** The eight directions drawTextOutlined stamps the outline in. */
const AROUND = [[-1, -1], [0, -1], [1, -1], [-1, 0], [1, 0], [-1, 1], [0, 1], [1, 1]];

/**
 * A square icon as RGB rows. The letter takes three fifths of the height, which keeps its outline
 * inside the middle 80% circle a launcher may cut a maskable icon down to, so one picture serves as
 * both kinds. Every edge lands on a whole pixel, so it stays as crisp as the font.
 */
function drawIcon(size: number): Uint8Array {
  const px = Math.max(1, Math.round(size * 0.079));
  // The title draws its letters at size 7 with an outline 3 wide.
  const th = Math.max(1, Math.round(px * 3 / 7));
  const x0 = Math.round((size - 5 * px) / 2), y0 = Math.round((size - 7 * px) / 2);
  const ink = (x: number, y: number): boolean => {
    const col = Math.floor((x - x0) / px), row = Math.floor((y - y0) / px);
    return row >= 0 && row < 7 && col >= 0 && col < 5 && G[row][col] === '#';
  };
  const out = new Uint8Array(size * size * 3);
  for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
    const rgb = ink(x, y) ? GOLD : AROUND.some(([dx, dy]) => ink(x - dx * th, y - dy * th)) ? OUTLINE : BG;
    out.set(rgb, (y * size + x) * 3);
  }
  return out;
}

/** Encode RGB rows as an 8-bit truecolour PNG. */
function png(size: number, rgb: Uint8Array): Buffer {
  const stride = size * 3;
  // Every row starts with its filter type, 0: stored as it is.
  const rows = Buffer.alloc((stride + 1) * size);
  for (let y = 0; y < size; y++) rows.set(rgb.subarray(y * stride, (y + 1) * stride), y * (stride + 1) + 1);
  const chunk = (type: string, data: Buffer): Buffer => {
    const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
    const len = Buffer.alloc(4), crc = Buffer.alloc(4);
    len.writeUInt32BE(data.length);
    crc.writeUInt32BE(zlib.crc32(body));
    return Buffer.concat([len, body, crc]);
  };
  const header = Buffer.alloc(13);
  header.writeUInt32BE(size, 0);
  header.writeUInt32BE(size, 4);
  header[8] = 8;   // bits per channel
  header[9] = 2;   // truecolour, no alpha: a home screen shows transparency as black anyway
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', header), chunk('IDAT', zlib.deflateSync(rows, { level: 9 })), chunk('IEND', Buffer.alloc(0)),
  ]);
}

function manifest(): string {
  return JSON.stringify({
    name: 'Gauntlet of Angband',
    short_name: 'Gauntlet',
    description: 'An Angband-style roguelike drawn like the 1985 arcade Gauntlet.',
    start_url: './',
    scope: './',
    display: 'fullscreen',
    // The game is drawn 16:9. Android holds an installed game to it; iOS ignores this and rotates.
    orientation: 'landscape',
    background_color: BACKGROUND,
    theme_color: BACKGROUND,
    categories: ['games'],
    icons: [
      { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: 'icon-512.png', sizes: '512x512', type: 'image/png' },
      { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  }, null, 2) + '\n';
}

/**
 * The service worker. Network first, so a new version is played the first time the game is opened
 * online; the copy kept from last time when the network is down or too slow to wait for. Its cache
 * is named for a hash of everything it keeps, so a deploy that changes anything is a new worker.
 */
function serviceWorker(version: string, files: string[]): string {
  return `// Generated by tools/pwa.ts.
const PREFIX = 'gauntlet-of-angband-';
const CACHE = PREFIX + ${JSON.stringify(version)};
const FILES = ${JSON.stringify(['./', ...files])};
/** How long to wait for the network before playing the kept copy. */
const PATIENCE_MS = 3000;
const MATCH = { ignoreSearch: true, ignoreVary: true };

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE)
    .then(cache => cache.addAll(FILES.map(f => new Request(f, { cache: 'reload' }))))
    .then(() => self.skipWaiting()));
});

self.addEventListener('activate', event => {
  // Other projects share this origin on GitHub Pages: only this game's old copies are cleared.
  event.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  const fresh = fetch(req).then(res => {
    if (!res.ok) return res;
    const copy = res.clone();
    return caches.open(CACHE).then(cache => cache.put(req, copy)).catch(() => {}).then(() => res);
  });
  // A download still going when the kept copy answers is kept for next time.
  event.waitUntil(fresh.catch(() => {}));
  event.respondWith(answer(req, fresh));
});

async function answer(req, fresh) {
  const late = new Promise(resolve => setTimeout(resolve, PATIENCE_MS));
  const res = await Promise.race([fresh, late]).catch(() => undefined);
  if (res && res.ok) return res;
  // No network, a slow one, or a bad answer (a broken deploy is a 404 for everything): the kept
  // copy plays instead. The game is one page, so whatever address a launch uses, it can answer.
  const cache = await caches.open(CACHE);
  const kept = await cache.match(req, MATCH) || (req.mode === 'navigate' && await cache.match('./', MATCH));
  return kept || fresh;
}
`;
}

export interface AppFile { type: string; body: Buffer }

/** Everything that sits beside the page, by the name it is asked for under. */
export function appFiles(page: string): Map<string, AppFile> {
  const icon = (size: number): AppFile => ({ type: 'image/png', body: png(size, drawIcon(size)) });
  const files = new Map<string, AppFile>([
    ['manifest.webmanifest', { type: 'application/manifest+json', body: Buffer.from(manifest()) }],
    ['icon-32.png', icon(32)],
    ['apple-touch-icon.png', icon(180)],
    ['icon-192.png', icon(192)],
    ['icon-512.png', icon(512)],
  ]);
  const hash = crypto.createHash('sha256').update(page);
  for (const [name, f] of files) hash.update(name).update(f.body);
  const sw = serviceWorker(hash.digest('hex').slice(0, 12), [...files.keys()]);
  files.set('sw.js', { type: 'text/javascript; charset=utf-8', body: Buffer.from(sw) });
  return files;
}
